version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      timezone: "Asia/Shanghai"
    labels:
      - "workflow"
      - "github_actions"